# Generated by Django 3.2.6 on 2021-08-13 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donateapp', '0002_auto_20210813_1309'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
