# Generated by Django 3.2.6 on 2021-08-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donateapp', '0004_auto_20210813_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150, unique=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
