# Generated by Django 3.2.6 on 2021-08-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donateapp', '0006_auto_20210814_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150, unique=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.CharField(blank=True, max_length=1500, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('contact', models.IntegerField(blank=True, max_length=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Ads',
        ),
    ]
