# Generated by Django 3.2.6 on 2021-08-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donateapp', '0007_auto_20210818_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
