# Generated by Django 3.2.6 on 2021-08-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donateapp', '0008_offers_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offers',
            name='contact',
        ),
        migrations.AddField(
            model_name='offers',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
