# Generated by Django 3.2.6 on 2021-08-18 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donateapp', '0011_alter_offers_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='donateapp.users'),
        ),
    ]
